# Doctrine Configuration
doctrine:
    dbal:
        ## SQLite
        driver:   "pdo_sqlite"
        path:     "%kernel.root_dir%/workshop.db"

        ## MySQL
        #driver:   "pdo_mysql"
        #host:     "localhost"
        #port:     "3306"
        #dbname:   "dcworkshop"
        #user:     "root"
        #password: ""
        #charset:  UTF8

        ## PostgreSQL
        #driver:   "pdo_pgsql"
        #host:     "localhost"
        #port:     "5432"
        #dbname:   "dcworkshop"
        #user:     "postgres"
        #password: ""
        #charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
