_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

QafooWorkshopBundle:
    resource: "@QafooWorkshopBundle/Controller/WorkshopController.php"
    type: auto

homepage:
    pattern: "/"
    defaults: { _controller: "QafooWorkshopBundle:Default:index" }

migrate:
    pattern: "/migrate"
    defaults: { _controller: "QafooWorkshopBundle:Default:migrate" }
    requirements: { _method: 'POST' }
