helloworld:
    pattern: "/hello"
    defaults: { _controller: "Qafoo\\WorkshopBundle\\Controller\\WorkshopController::helloWorldAction" }

service_hello:
    pattern: "/service-hello"
    defaults: { _controller: "QafooWorkshop.Controller.Service:helloAction" }
